### ISSUE TITLE
Requesting some infos

### ISSUE THREAD

**Issue by Stinocon** [jnicolson/panasonic_ac_wifi#1]
Wow! 
This project seems to be right up my alley! I have two Panasonic CZ-TACG1's built into Home Assistant but as we know they are not very reliable.
I was a bit put off by the other projects because I'm not very good at soldering but if I understand correctly I should just get this one manufactured, get a cable, put ESPHome in it and plug it in. That's it.

I have some questions:

1) Can you link me where exactly to buy the cable that is needed? Or at least a picture of the two ends so I can look for it in some EU store.
2) To flash other ESP modules I normally use dupont cables (I think they are called like that) and then connect them to a USB programmer... Does this work in the same way? I guess I have to use the PINs on the "white" connector.

Thanks!

**Comment by jnicolson** [comment]
Hi,
Yes in theory someone like JLCPCB and their assembly service should be able to assemble this for you - I assembled this myself but all the parts were from LCSC so i think that means they should all be available at JLC (and there's probably others - JLC is just the one i'm aware of).

I don't think you could buy a pre-made cable unfortuantely.  The picoblade end you can - something like this: https://www.adafruit.com/product/4722 the female end should plug straight in to controller board.  For the air conditioner end, JST PA doesn't seem to be very popular with makers, it's easy to get JST-PH cables but not JST-PA.  If you really wanted to avoid crimping you could probably buy something like https://www.digikey.com/en/products/detail/jst-sales-america-inc/APAPA22K152/6009461 along with the housing https://www.digikey.com/en/products/detail/jst-sales-america-inc/PAP-05V-S/759977 .  You would then just need to join the picoblade tail to the JST-PA jumpers and insert them into the housing (making sure the get the pinout correct).  Joining them I would solder but if you're really against soldering then you could use a wago connector without issue.

To flash you could insert dupont connectors into the header to the right of the ESP32 - if you have an ESP32 type programmer then you don't need to do anything but if it's just a USB to serial adapter then you'll have to put it into programming mode manually (pull IO0/BOOT to ground by connecting a jumper between them then pull RESET to ground to reset it into boot mode).  It'd be a bit difficult as you would need to keep pressure on dupont connectors to make contact but you only have to do it once I guess?

Hope this answers your questions!

**Comment by Romkabouter** [comment]
I have order 5 units from JLCPCB and I can confirm they work.
You should however use GPIO4 fro RX and GPIO16 for TX, this can also be found in the schematic

This was my order.
<img width="397" alt="image" src="https://github.com/jnicolson/panasonic_ac_wifi/assets/4774478/3c0675b6-042e-4c7c-a142-89fe3132ae5c">

I have installed 1 in an airco, but need some connectors to install the second. 
Integrates fine with HA

<img width="329" alt="image" src="https://github.com/jnicolson/panasonic_ac_wifi/assets/4774478/da2c4bfb-7e57-4fbb-93f5-3c3b150e8832">


<img width="340" alt="image" src="https://github.com/jnicolson/panasonic_ac_wifi/assets/4774478/9ad29c28-4bd3-4c74-b564-4cf6f4280fe0">

**Comment by Romkabouter** [comment]
Note that my units have a header on U3

**Comment by dvanp** [comment]
> I have order 5 units from JLCPCB and I can confirm they work. You should however use GPIO4 fro RX and GPIO16 for TX, this can also be found in the schematic
> 
> This was my order. <img alt="image" width="397" src="https://user-images.githubusercontent.com/4774478/262982239-3c0675b6-042e-4c7c-a142-89fe3132ae5c.png">
> 
> I have installed 1 in an airco, but need some connectors to install the second. Integrates fine with HA
> 
> <img alt="image" width="329" src="https://user-images.githubusercontent.com/4774478/262983312-da2c4bfb-7e57-4fbb-93f5-3c3b150e8832.png"> <img alt="image" width="340" src="https://user-images.githubusercontent.com/4774478/262983399-9ad29c28-4bd3-4c74-b564-4cf6f4280fe0.png">

That's great! Would you be willing to share the files you used to order at JLCPCB?

**Comment by Romkabouter** [comment]
Sure, I ran into so problems with the positioning so I will try and fix that. Other people should be able to upload and order without those issues :)

**Comment by Romkabouter** [comment]
Attached is a gerberfiles.zip, this includes the drill files and all. Also attached is a bom.csv (bill of materials) and a cpl.csv (the position file)
[bom.csv](https://github.com/jnicolson/panasonic_ac_wifi/files/12438439/bom.csv)
[cpl.csv](https://github.com/jnicolson/panasonic_ac_wifi/files/12438440/cpl.csv)
[gerberfiles.zip](https://github.com/jnicolson/panasonic_ac_wifi/files/12438441/gerberfiles.zip)

**Comment by dvanp** [comment]
> Attached is a gerberfiles.zip, this includes the drill files and all. Also attached is a bom.csv (bill of materials) and a cpl.csv (the position file) [bom.csv](https://github.com/jnicolson/panasonic_ac_wifi/files/12438439/bom.csv) [cpl.csv](https://github.com/jnicolson/panasonic_ac_wifi/files/12438440/cpl.csv) [gerberfiles.zip](https://github.com/jnicolson/panasonic_ac_wifi/files/12438441/gerberfiles.zip)

Thanks, I've just ordered 5 as well!

**Comment by Romkabouter** [comment]
This is my config:

```
esphome:

  name: airco-bedroom
  friendly_name: Airco bedroom

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  password: !secret wifi_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Airco-Bedroom Fallback Hotspot"
    password: "vRXDT1a6XiNW"

captive_portal:

uart:
  tx_pin: GPIO16
  rx_pin: GPIO4
  baud_rate: 9600
  parity: EVEN
    
external_components:
  source: github://DomiStyle/esphome-panasonic-ac
  components: [panasonic_ac]

climate:
  - platform: panasonic_ac
    type: cnt
    name: AC Bedroom
    horizontal_swing_select:
      name: AC Bedroom Horizontal Swing Mode
    vertical_swing_select:
      name: AC Bedroom Vertical Swing Mode
    outside_temperature:
      name: AC Bedroom Outside Temperature
    current_power_consumption:
      name: AC Bedroom Power Consumption
```
